services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    restart: unless-stopped
    command: npm run dev
  app2:
    build:
      context: ./chatgpt-bridge-main/server
    container_name: chatgpt-bridge-main
    ports:
      - "4000:4000"
    volumes:
      - ./chatgpt-bridge-main/server:/server
      - /app/node_modules
    depends_on:
      - redis
      - app
    restart: unless-stopped
    command: npm start
  redis:
    image: redis:7
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: